### ISSUE TITLE
Click on post set draggable

### ISSUE THREAD

**Issue by jacobparis** [ephemer/meteor-css3d#1]
Hey, I'm using this to allow users to swipe left on a post to delete it. Once I make it draggable though, they are unable to access the input to type new comments on the post. Is there any way around this? Do you call stopPropagation() or something that hijacks my click? If so, would that break things by removing?

**Comment by jacobparis** [comment]
I forked this into my own project so I can modify the code. Is there any way to drag two non-nested onjects at once?

**Comment by ephemer** [comment]
Hi @JacobPariseau thanks for the questions. The clicks shouldn't get hijacked as such, there are checks in there that specifically _avoid_ stopPropagation when the user just clicks instead of dragging.

As for two objects at once, you could just set an onUpdate function in your SimpleDrag initialiser. The function receives (draggedObjectCurrentX, maxX) so you could just set the other object to an offset of currentX: `css3dObjectRefOfTheOtherObject.setX(draggedObjectCurrentX)`
